server:
  #配置端口号
  port: 8080
#  servlet:
#    #项目访问前缀
#    context-path: /myspringboot
spring:
  #profiles:
  #  active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      #池中维护的最小空闲连接数
      minimum-idle: 5
      #池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 15
      #自动提交从池中返回的连接
      auto-commit: true
      #连接允许在池中闲置的最长时间
      idle-timeout: 30000
      #连接池的用户定义名称，主要出现在日志记录和JMX管理控制台中以识别池和池配置
      #pool-name: DatebookHikariCP
      #池中连接最长生命周期
      max-lifetime: 1800000
      #等待来自池的连接的最大毫秒数
      connection-timeout: 60000
      connection-init-sql: set names utf8mb4
    url: jdbc:mysql://localhost:3306/cafeteria_menu?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    #url:  jdbc:mysql://115.28.72.235:3306/yqjcwd?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    username: root
    password:
    #password: xiaosage8632!
  servlet:
    multipart:
      enabled: false
      max-file-size: 50MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:mapping/*.xml
  typeAliasesPackage: com.example.hwmenu.dao
img:
  path: /static/img




